-- H2 in PostgreSQL compatibility mode, used by the optional `local` profile only.
-- Production uses PostgreSQL with db/schema.sql.
CREATE TABLE IF NOT EXISTS task_definitions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(512) NOT NULL,
    kind             VARCHAR(32)  NOT NULL,
    interval_seconds BIGINT,
    hour             INTEGER,
    minute           INTEGER,
    zone_id          VARCHAR(64),
    anchor_utc       TIMESTAMP WITH TIME ZONE NOT NULL,
    state            VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_task_kind CHECK (kind IN ('FIXED_INTERVAL', 'DAILY_LOCAL')),
    CONSTRAINT ck_task_state CHECK (state IN ('ACTIVE', 'PAUSED'))
);

CREATE TABLE IF NOT EXISTS trigger_instances (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id          BIGINT NOT NULL,
    ordinal          INTEGER NOT NULL,
    state            VARCHAR(32) NOT NULL,
    dst_note         VARCHAR(64) NOT NULL,
    nominal_local    TIMESTAMP NOT NULL,
    actual_utc       TIMESTAMP WITH TIME ZONE,
    actual_local     TIMESTAMP,
    utc_offset       VARCHAR(16),
    explanation      VARCHAR(1024) NOT NULL,
    generated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_instances_task FOREIGN KEY (task_id)
        REFERENCES task_definitions(id) ON DELETE CASCADE,
    CONSTRAINT ck_instance_state
        CHECK (state IN ('SCHEDULED', 'SUPPRESSED', 'FIRED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_trigger_instances_task_ordinal
    ON trigger_instances(task_id, ordinal);
