-- PostgreSQL schema for the recurring-task workbench.
-- Quartz itself runs on the in-memory RAMJobStore; these tables hold our task definitions and
-- the generated trigger instances (including suppressed DST-gap entries).

CREATE TABLE IF NOT EXISTS task_definitions (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             TEXT        NOT NULL,
    kind             TEXT        NOT NULL CHECK (kind IN ('FIXED_INTERVAL', 'DAILY_LOCAL')),
    interval_seconds BIGINT,
    hour             INTEGER,
    minute           INTEGER,
    zone_id          TEXT,
    anchor_utc       TIMESTAMPTZ NOT NULL,
    state            TEXT        NOT NULL DEFAULT 'ACTIVE'
                       CHECK (state IN ('ACTIVE', 'PAUSED')),
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS trigger_instances (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id          BIGINT NOT NULL REFERENCES task_definitions(id) ON DELETE CASCADE,
    ordinal          INTEGER NOT NULL,
    state            TEXT NOT NULL CHECK (state IN ('SCHEDULED', 'SUPPRESSED', 'FIRED')),
    dst_note         TEXT NOT NULL,
    nominal_local    TIMESTAMP NOT NULL,
    actual_utc       TIMESTAMPTZ,
    actual_local     TIMESTAMP,
    utc_offset       TEXT,
    explanation      TEXT NOT NULL,
    generated_at     TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_trigger_instances_task
    ON trigger_instances(task_id, ordinal);
CREATE UNIQUE INDEX IF NOT EXISTS uq_trigger_instances_task_ordinal
    ON trigger_instances(task_id, ordinal);
